"""
考研英语高频词汇批量导入脚本
适配实际表结构: word, phonetic, basic_meaning
用法：cd backend && python seed_kaoyan_words.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from supabase_client import get_supabase

# 考研英语核心高频词汇 - 格式：[word, phonetic, basic_meaning]
WORDS = [
    ["abstract", "/ˈæbstrækt/", "adj. 抽象的；n. 摘要"],
    ["abundant", "/əˈbʌndənt/", "adj. 丰富的，充裕的"],
    ["academic", "/ˌækəˈdemɪk/", "adj. 学术的；学院的"],
    ["accelerate", "/əkˈseləreɪt/", "v. 加速；促进"],
    ["access", "/ˈækses/", "n./v. 进入；通道；访问"],
    ["accommodate", "/əˈkɒmədeɪt/", "v. 容纳；提供住宿；适应"],
    ["accompany", "/əˈkʌmpəni/", "v. 陪伴；伴随"],
    ["accomplish", "/əˈkʌmplɪʃ/", "v. 完成；实现"],
    ["accumulate", "/əˈkjuːmjəleɪt/", "v. 积累；积聚"],
    ["accurate", "/ˈækjərət/", "adj. 精确的，准确的"],
    ["acknowledge", "/əkˈnɒlɪdʒ/", "v. 承认；确认；感谢"],
    ["acquire", "/əˈkwaɪər/", "v. 获得；习得"],
    ["adapt", "/əˈdæpt/", "v. 适应；改编"],
    ["adequate", "/ˈædɪkwət/", "adj. 足够的；适当的"],
    ["adjust", "/əˈdʒʌst/", "v. 调整；适应"],
    ["administration", "/ədˌmɪnɪˈstreɪʃn/", "n. 管理；行政；政府"],
    ["adopt", "/əˈdɒpt/", "v. 采用；收养"],
    ["advocate", "/ˈædvəkeɪt/", "v. 提倡；n. 拥护者"],
    ["affect", "/əˈfekt/", "v. 影响；感动"],
    ["aggressive", "/əˈɡresɪv/", "adj. 侵略的；好斗的；进取的"],
    ["allocate", "/ˈæləkeɪt/", "v. 分配；拨出"],
    ["alternative", "/ɔːlˈtɜːnətɪv/", "n./adj. 替代方案；替代的"],
    ["ambiguous", "/æmˈbɪɡjuəs/", "adj. 模棱两可的；含糊的"],
    ["ambitious", "/æmˈbɪʃəs/", "adj. 有雄心的；野心勃勃的"],
    ["analyze", "/ˈænəlaɪz/", "v. 分析；解析"],
    ["anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期；期望；抢先"],
    ["apparent", "/əˈpærənt/", "adj. 明显的；表面上的"],
    ["approach", "/əˈprəʊtʃ/", "n./v. 方法；接近"],
    ["appropriate", "/əˈprəʊpriət/", "adj. 适当的；合适的"],
    ["approve", "/əˈpruːv/", "v. 批准；赞成"],
    ["arise", "/əˈraɪz/", "v. 出现；产生"],
    ["artificial", "/ˌɑːtɪˈfɪʃl/", "adj. 人工的；人造的；虚假的"],
    ["assemble", "/əˈsembl/", "v. 集合；组装"],
    ["assess", "/əˈses/", "v. 评估；评定"],
    ["assign", "/əˈsaɪn/", "v. 分配；指派"],
    ["associate", "/əˈsəʊʃieɪt/", "v./n. 联系；关联"],
    ["assume", "/əˈsjuːm/", "v. 假设；承担"],
    ["attain", "/əˈteɪn/", "v. 达到；获得"],
    ["attribute", "/əˈtrɪbjuːt/", "n./v. 属性；归因于"],
    ["authority", "/ɔːˈθɒrəti/", "n. 权威；当局；权力"],
    ["available", "/əˈveɪləbl/", "adj. 可用的；有空的"],
    ["aware", "/əˈweər/", "adj. 意识到的；知道的"],
    ["barrier", "/ˈbæriər/", "n. 障碍；屏障"],
    ["benefit", "/ˈbenɪfɪt/", "n./v. 利益；好处；有益于"],
    ["bias", "/ˈbaɪəs/", "n./v. 偏见；偏向"],
    ["boom", "/buːm/", "n./v. 繁荣；激增"],
    ["boundary", "/ˈbaʊndri/", "n. 边界；界限"],
    ["budget", "/ˈbʌdʒɪt/", "n./v. 预算"],
    ["burden", "/ˈbɜːdn/", "n./v. 负担；重担"],
    ["capable", "/ˈkeɪpəbl/", "adj. 有能力的"],
    ["capacity", "/kəˈpæsəti/", "n. 能力；容量；产能"],
    ["category", "/ˈkætəɡəri/", "n. 类别；范畴"],
    ["challenge", "/ˈtʃælɪndʒ/", "n./v. 挑战；质疑"],
    ["channel", "/ˈtʃænl/", "n./v. 频道；渠道；海峡"],
    ["circumstance", "/ˈsɜːkəmstəns/", "n. 环境；情况；境遇"],
    ["collapse", "/kəˈlæps/", "v./n. 倒塌；崩溃；暴跌"],
    ["colleague", "/ˈkɒliːɡ/", "n. 同事；同僚"],
    ["commit", "/kəˈmɪt/", "v. 犯（罪）；承诺；投入"],
    ["communicate", "/kəˈmjuːnɪkeɪt/", "v. 交流；传达；通讯"],
    ["community", "/kəˈmjuːnəti/", "n. 社区；群体；共同体"],
    ["compensate", "/ˈkɒmpenseɪt/", "v. 补偿；赔偿；弥补"],
    ["compete", "/kəmˈpiːt/", "v. 竞争；比赛；对抗"],
    ["complex", "/ˈkɒmpleks/", "adj./n. 复杂的；综合体"],
    ["component", "/kəmˈpəʊnənt/", "n. 组成部分；组件；成分"],
    ["comprehensive", "/ˌkɒmprɪˈhensɪv/", "adj. 全面的；综合的；详尽的"],
    ["concentrate", "/ˈkɒnsntreɪt/", "v. 集中；专注；浓缩"],
    ["concept", "/ˈkɒnsept/", "n. 概念；观念；思想"],
    ["conduct", "/kənˈdʌkt/", "v./n. 进行；实施；行为；指挥"],
    ["confident", "/ˈkɒnfɪdənt/", "adj. 自信的；确信的"],
    ["conflict", "/ˈkɒnflɪkt/", "n./v. 冲突；矛盾；斗争"],
    ["conscious", "/ˈkɒnʃəs/", "adj. 有意识的；清醒的；注意到的"],
    ["consequence", "/ˈkɒnsɪkwəns/", "n. 结果；后果；重要性"],
    ["conservative", "/kənˈsɜːvətɪv/", "adj./n. 保守的；守旧的；保守派"],
    ["considerable", "/kənˈsɪdərəbl/", "adj. 相当大的；可观的；重要的"],
    ["consistent", "/kənˈsɪstənt/", "adj. 一致的；始终如一的；连贯的"],
    ["constant", "/ˈkɒnstənt/", "adj./n. 持续的；不变的；常数"],
    ["constitute", "/ˈkɒnstɪtjuːt/", "v. 构成；组成；设立"],
    ["construct", "/kənˈstrʌkt/", "v. 建造；构建；创立"],
    ["consume", "/kənˈsjuːm/", "v. 消耗；消费；耗尽"],
    ["contemporary", "/kənˈtemprəri/", "adj./n. 当代的；同时代的"],
    ["context", "/ˈkɒntekst/", "n. 上下文；背景；语境"],
    ["contract", "/ˈkɒntrækt/", "n./v. 合同；契约；收缩"],
    ["contribute", "/kənˈtrɪbjuːt/", "v. 贡献；捐献；导致；投稿"],
    ["controversial", "/ˌkɒntrəˈvɜːʃl/", "adj. 有争议的；引起争论的"],
    ["conventional", "/kənˈvenʃənl/", "adj. 传统的；常规的；惯例的"],
    ["convey", "/kənˈveɪ/", "v. 传达；表达；运送；传递"],
    ["convince", "/kənˈvɪns/", "v. 使信服；说服；使确信"],
    ["cooperate", "/kəʊˈɒpəreɪt/", "v. 合作；协作；配合"],
    ["coordinate", "/kəʊˈɔːdɪneɪt/", "v./n. 协调；配合；坐标"],
    ["crisis", "/ˈkraɪsɪs/", "n. 危机；紧要关头；转折点"],
    ["criterion", "/kraɪˈtɪəriən/", "n. 标准；准则；评判依据"],
    ["crucial", "/ˈkruːʃl/", "adj. 至关重要的；决定性的"],
    ["cultivate", "/ˈkʌltɪveɪt/", "v. 培养；耕作；陶冶"],
    ["debate", "/dɪˈbeɪt/", "n./v. 辩论；争论；讨论"],
    ["decline", "/dɪˈklaɪn/", "v./n. 下降；衰退；谢绝；婉拒"],
    ["dedicate", "/ˈdedɪkeɪt/", "v. 奉献；致力于；题献"],
    ["define", "/dɪˈfaɪn/", "v. 定义；界定；明确"],
    ["demonstrate", "/ˈdemənstreɪt/", "v. 演示；证明；示威；表明"],
    ["deny", "/dɪˈnaɪ/", "v. 否认；拒绝；否定"],
    ["depict", "/dɪˈpɪkt/", "v. 描绘；描述；刻画"],
    ["derive", "/dɪˈraɪv/", "v. 源自；获得；推导"],
    ["deserve", "/dɪˈzɜːv/", "v. 值得；应得；应受"],
    ["despite", "/dɪˈspaɪt/", "prep. 尽管；不管；虽然"],
    ["detect", "/dɪˈtekt/", "v. 检测；发现；探测；察觉"],
    ["determine", "/dɪˈtɜːmɪn/", "v. 决定；确定；下决心"],
    ["device", "/dɪˈvaɪs/", "n. 设备；装置；手段；策略"],
    ["dimension", "/daɪˈmenʃn/", "n. 维度；尺寸；方面；范围"],
    ["discrimination", "/dɪˌskrɪmɪˈneɪʃn/", "n. 歧视；辨别；区别对待"],
    ["distinguish", "/dɪˈstɪŋɡwɪʃ/", "v. 区分；辨别；使杰出"],
    ["distribute", "/dɪˈstrɪbjuːt/", "v. 分发；分配；分布；散布"],
    ["diverse", "/daɪˈvɜːs/", "adj. 多样的；不同的；多元的"],
    ["domestic", "/dəˈmestɪk/", "adj. 国内的；家庭的；驯养的"],
    ["dominate", "/ˈdɒmɪneɪt/", "v. 支配；主导；控制；俯视"],
    ["dramatic", "/drəˈmætɪk/", "adj. 戏剧性的；引人注目的；急剧的"],
    ["dynamic", "/daɪˈnæmɪk/", "adj. 动态的；充满活力的；不断变化的"],
    ["economical", "/ˌiːkəˈnɒmɪkl/", "adj. 经济的；节约的；实惠的"],
    ["eliminate", "/ɪˈlɪmɪneɪt/", "v. 消除；淘汰；根除"],
    ["emerge", "/ɪˈmɜːdʒ/", "v. 出现；浮现；显露；兴起"],
    ["emphasis", "/ˈemfəsɪs/", "n. 强调；重点；重视"],
    ["enable", "/ɪˈneɪbl/", "v. 使能够；启用；授权"],
    ["enhance", "/ɪnˈhɑːns/", "v. 增强；提高；改善"],
    ["enormous", "/ɪˈnɔːməs/", "adj. 巨大的；庞大的"],
    ["ensure", "/ɪnˈʃʊər/", "v. 确保；保证；担保"],
    ["enterprise", "/ˈentəpraɪz/", "n. 企业；事业；进取心"],
    ["enthusiasm", "/ɪnˈθjuːziæzəm/", "n. 热情；热忱；狂热"],
    ["environment", "/ɪnˈvaɪrənmənt/", "n. 环境；周围状况"],
    ["equivalent", "/ɪˈkwɪvələnt/", "adj./n. 等价的；等同物；相当的"],
    ["essential", "/ɪˈsenʃl/", "adj./n. 基本的；必不可少的；本质"],
    ["establish", "/ɪˈstæblɪʃ/", "v. 建立；设立；确立；证实"],
    ["evaluate", "/ɪˈvæljueɪt/", "v. 评估；评价；估值"],
    ["eventually", "/ɪˈventʃuəli/", "adv. 最终；终于；终究"],
    ["evidence", "/ˈevɪdəns/", "n./v. 证据；证明；迹象"],
    ["evolution", "/ˌiːvəˈluːʃn/", "n. 进化；演变；发展"],
    ["exceed", "/ɪkˈsiːd/", "v. 超过；超越；超出"],
    ["exclude", "/ɪkˈskluːd/", "v. 排除；不包括；排斥"],
    ["expand", "/ɪkˈspænd/", "v. 扩大；扩展；膨胀；详述"],
    ["exploit", "/ɪkˈsplɔɪt/", "v. 开发；利用；剥削；n. 功绩"],
    ["external", "/ɪkˈstɜːnl/", "adj. 外部的；外来的；表面的"],
    ["facilitate", "/fəˈsɪlɪteɪt/", "v. 促进；使便利；推动"],
    ["feature", "/ˈfiːtʃər/", "n./v. 特征；特色；以…为特色"],
    ["flexible", "/ˈfleksəbl/", "adj. 灵活的；柔韧的；可变通的"],
    ["foundation", "/faʊnˈdeɪʃn/", "n. 基础；基金会；根据；创立"],
    ["fundamental", "/ˌfʌndəˈmentl/", "adj./n. 基本的；根本的；基础"],
    ["generate", "/ˈdʒenəreɪt/", "v. 产生；生成；引起"],
    ["guarantee", "/ˌɡærənˈtiː/", "v./n. 保证；担保；保修单"],
    ["identify", "/aɪˈdentɪfaɪ/", "v. 识别；确认；鉴定；认同"],
    ["illustrate", "/ˈɪləstreɪt/", "v. 说明；阐明；举例；加插图"],
    ["impact", "/ˈɪmpækt/", "n./v. 影响；冲击；撞击"],
    ["implement", "/ˈɪmplɪment/", "v./n. 实施；执行；工具；器具"],
    ["implication", "/ˌɪmplɪˈkeɪʃn/", "n. 含义；暗示；影响；牵连"],
    ["impose", "/ɪmˈpəʊz/", "v. 强加；征收；推行；迫使"],
    ["incentive", "/ɪnˈsentɪv/", "n. 激励；动机；刺激"],
    ["incorporate", "/ɪnˈkɔːpəreɪt/", "v. 合并；包含；纳入；组建"],
    ["indicate", "/ˈɪndɪkeɪt/", "v. 表明；指示；暗示"],
    ["individual", "/ˌɪndɪˈvɪdʒuəl/", "adj./n. 个人的；个体；独特的"],
    ["infrastructure", "/ˈɪnfrəstrʌktʃər/", "n. 基础设施；基础建设"],
    ["innovation", "/ˌɪnəˈveɪʃn/", "n. 创新；革新；新方法"],
    ["integrate", "/ˈɪntɪɡreɪt/", "v. 整合；融入；使一体化"],
    ["intellectual", "/ˌɪntəˈlektʃuəl/", "adj./n. 智力的；知识分子"],
    ["intense", "/ɪnˈtens/", "adj. 强烈的；激烈的；紧张的"],
    ["interpret", "/ɪnˈtɜːprɪt/", "v. 解释；口译；理解为；诠释"],
    ["invest", "/ɪnˈvest/", "v. 投资；投入；赋予"],
    ["involve", "/ɪnˈvɒlv/", "v. 涉及；包含；参与；牵涉"],
    ["isolate", "/ˈaɪsəleɪt/", "v. 隔离；孤立；分离"],
    ["justify", "/ˈdʒʌstɪfaɪ/", "v. 证明…正当；为…辩护"],
    ["legislation", "/ˌledʒɪsˈleɪʃn/", "n. 立法；法规；法律"],
    ["liberal", "/ˈlɪbərəl/", "adj./n. 自由的；开明的；自由主义者"],
    ["maintain", "/meɪnˈteɪn/", "v. 维持；保养；坚持；主张"],
    ["manipulate", "/məˈnɪpjuleɪt/", "v. 操纵；控制；操作；处理"],
    ["mechanism", "/ˈmekənɪzəm/", "n. 机制；机械装置；原理"],
    ["migrate", "/maɪˈɡreɪt/", "v. 迁移；移居；迁徙"],
    ["minimize", "/ˈmɪnɪmaɪz/", "v. 最小化；降到最低；贬低"],
    ["motivate", "/ˈməʊtɪveɪt/", "v. 激励；激发；促进"],
    ["neglect", "/nɪˈɡlekt/", "v./n. 忽视；疏忽；忽略"],
    ["notion", "/ˈnəʊʃn/", "n. 概念；观念；想法"],
    ["objective", "/əbˈdʒektɪv/", "adj./n. 客观的；目标；目的"],
    ["obtain", "/əbˈteɪn/", "v. 获得；得到；存在"],
    ["obvious", "/ˈɒbviəs/", "adj. 明显的；显然的"],
    ["optimistic", "/ˌɒptɪˈmɪstɪk/", "adj. 乐观的；乐观主义的"],
    ["overcome", "/ˌəʊvəˈkʌm/", "v. 克服；战胜；压倒"],
    ["participate", "/pɑːˈtɪsɪpeɪt/", "v. 参加；参与；分享"],
    ["perceive", "/pəˈsiːv/", "v. 感知；理解；察觉；认为"],
    ["phenomenon", "/fɪˈnɒmɪnən/", "n. 现象；奇迹；杰出人才"],
    ["philosophy", "/fɪˈlɒsəfi/", "n. 哲学；理念；人生观"],
    ["potential", "/pəˈtenʃl/", "adj./n. 潜在的；潜力；可能性"],
    ["prejudice", "/ˈpredʒədɪs/", "n./v. 偏见；歧视；损害"],
    ["preserve", "/prɪˈzɜːv/", "v./n. 保存；保护；保护区；果酱"],
    ["principle", "/ˈprɪnsəpl/", "n. 原则；原理；准则；信念"],
    ["priority", "/praɪˈɒrəti/", "n. 优先权；优先事项；重点"],
    ["procedure", "/prəˈsiːdʒər/", "n. 程序；步骤；手续；流程"],
    ["profound", "/prəˈfaʊnd/", "adj. 深远的；深刻的；渊博的"],
    ["promote", "/prəˈməʊt/", "v. 促进；提升；推广；晋升"],
    ["proportion", "/prəˈpɔːʃn/", "n. 比例；部分；份额；均衡"],
    ["prospect", "/ˈprɒspekt/", "n./v. 前景；展望；勘探；可能性"],
    ["psychological", "/ˌsaɪkəˈlɒdʒɪkl/", "adj. 心理的；心理学的"],
    ["purchase", "/ˈpɜːtʃəs/", "v./n. 购买；采购"],
    ["pursue", "/pəˈsjuː/", "v. 追求；追逐；从事；继续"],
    ["radical", "/ˈrædɪkl/", "adj./n. 激进的；根本的；自由基"],
    ["rational", "/ˈræʃnəl/", "adj. 理性的；合理的；理智的"],
    ["relevant", "/ˈreləvənt/", "adj. 相关的；切题的；有价值的"],
    ["reluctant", "/rɪˈlʌktənt/", "adj. 不情愿的；勉强的"],
    ["representative", "/ˌreprɪˈzentətɪv/", "n./adj. 代表；代表性的；典型的"],
    ["reputation", "/ˌrepjuˈteɪʃn/", "n. 名声；名誉；声望"],
    ["resolve", "/rɪˈzɒlv/", "v./n. 解决；决心；决议；分解"],
    ["resource", "/rɪˈsɔːs/", "n. 资源；财力；智谋"],
    ["respond", "/rɪˈspɒnd/", "v. 回应；响应；回答；反应"],
    ["restore", "/rɪˈstɔːr/", "v. 恢复；修复；归还；复原"],
    ["restrict", "/rɪˈstrɪkt/", "v. 限制；约束；限定"],
    ["reveal", "/rɪˈviːl/", "v. 揭示；透露；展现；揭露"],
    ["revolution", "/ˌrevəˈluːʃn/", "n. 革命；变革；彻底改变"],
    ["scheme", "/skiːm/", "n./v. 计划；方案；阴谋；策划"],
    ["security", "/sɪˈkjʊərəti/", "n. 安全；保障；证券；安保"],
    ["significant", "/sɪɡˈnɪfɪkənt/", "adj. 显著的；重要的；有意义的"],
    ["strategy", "/ˈstrætədʒi/", "n. 策略；战略；规划"],
    ["substitute", "/ˈsʌbstɪtjuːt/", "n./v. 替代品；代替；替换"],
    ["sufficient", "/səˈfɪʃnt/", "adj. 足够的；充分的"],
    ["sustain", "/səˈsteɪn/", "v. 维持；支撑；遭受；经受"],
    ["symbolic", "/sɪmˈbɒlɪk/", "adj. 象征的；符号的"],
    ["tendency", "/ˈtendənsi/", "n. 趋势；倾向；癖好"],
    ["transform", "/trænsˈfɔːm/", "v. 转变；改造；转化"],
    ["ultimate", "/ˈʌltɪmət/", "adj./n. 最终的；根本的；终极"],
    ["undergo", "/ˌʌndəˈɡəʊ/", "v. 经历；遭受；承受"],
    ["undertake", "/ˌʌndəˈteɪk/", "v. 承担；从事；承诺；着手"],
    ["universal", "/ˌjuːnɪˈvɜːsl/", "adj. 普遍的；全体的；通用的"],
    ["valid", "/ˈvælɪd/", "adj. 有效的；合理的；合法的"],
    ["vary", "/ˈveəri/", "v. 变化；不同；改变"],
    ["version", "/ˈvɜːʃn/", "n. 版本；说法；译文"],
    ["virtual", "/ˈvɜːtʃuəl/", "adj. 虚拟的；实质上的"],
    ["vision", "/ˈvɪʒn/", "n. 视力；愿景；远见；幻觉"],
    ["visual", "/ˈvɪʒuəl/", "adj. 视觉的；视力的"],
    ["welfare", "/ˈwelfeər/", "n. 福利；幸福；社会保障"],
]

def seed():
    supabase = get_supabase()
    added = skipped = errors = 0
    total = len(WORDS)

    for i, w in enumerate(WORDS):
        word, phonetic, meaning = w
        try:
            existing = supabase.table('words').select('id').eq('word', word).execute()
            if existing.data:
                skipped += 1
                print(f"[{i+1}/{total}] 跳过: {word} (已存在)")
                continue
            supabase.table('words').insert({
                'word': word,
                'phonetic': phonetic,
                'basic_meaning': meaning
            }).execute()
            added += 1
            print(f"[{i+1}/{total}] 已添加: {word}")
        except Exception as e:
            errors += 1
            print(f"[{i+1}/{total}] 错误: {word} - {e}")

    print(f"\n===== 导入完成 =====")
    print(f"新增: {added} | 跳过: {skipped} | 失败: {errors}")

if __name__ == '__main__':
    seed()
